name: Sourcemod CI

on:
  push:
    branches: [ "sourcemod" ]
  pull_request:
    branches: [ "sourcemod" ]

  workflow_dispatch:

env:
  REPO_NAME: "${{ github.event.repository.name }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile Sourcepawn Plugin
        uses: SheplyRam/compile-sourcepawn-plugin@v1
        with:
          input: scripting/sm_hosties_e.sp
          output: plugins/sm_hosties_e.smx
          includes: "scripting/include scripting/hosties"
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: "${{ env.REPO_NAME }}-${{ env.BUILD_NUMBER }}"
          path: |
            ./
            !.git
            !.github
            !.gitignore
